name: 'Create Release'
description: 'Create Git tag and GitHub release'
inputs:
  version:
    description: 'Version to release'
    required: true
  channel:
    description: 'Release channel (beta, alpha, latest, next)'
    required: true
  github-token:
    description: 'GitHub token for authentication'
    required: true

runs:
  using: "composite"
  steps:
    - name: Create Git Tag
      shell: bash
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git tag -a v${{ inputs.version }} -m "Release v${{ inputs.version }}"
        git push origin v${{ inputs.version }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ inputs.version }}
        name: Release v${{ inputs.version }} ${{ inputs.channel == 'latest' && 'Latest' || inputs.channel }}
        body: |
          ## Changes

          This release includes the following platform-specific binaries:
          - macOS (ARM64)
          - Windows (x64)
          - Linux (x64)
        draft: false
        prerelease: ${{ inputs.channel != 'latest' }}
        discussion_category_name: Announcements
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }} 
