name: Test Release (Dry Run)
run-name: Test Release ${{ github.ref_name }} (pushed by ${{ github.actor }})

on:
  workflow_dispatch:
    inputs:
      channel:
        description: 'NPM tag to publish to'
        type: choice
        options:
          - beta
          - alpha
          - latest
          - next
        default: beta
permissions:
  contents: read

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: '.nvmrc'
      - uses: ./.github/actions/verify-version
        id: verify-version
    outputs:
      version: ${{ steps.verify-version.outputs.version }}

  test:
    runs-on: ubuntu-latest
    needs: check-version
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: '.nvmrc'
      - run: npm ci
      - run: npm run build
      - run: npm test
      - run: npm run test:e2e

  upload-assets:
    runs-on: ubuntu-latest
    needs: [check-version, test]
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'

      # Build
      - run: npm ci
      - run: npm run build

      # Build platform-specific tarballs
      - name: Install linux toolchain
        run: |
          sudo apt update
          sudo apt install nsis p7zip-full p7zip-rar -y

      - name: Build all tarballs in parallel
        run: |
          npx oclif pack tarballs --targets=linux-x64,win32-x64,darwin-arm64 --no-xz --parallel

  npm-publish:
    runs-on: ubuntu-latest
    needs: [check-version, test, upload-assets]
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'

      # Clean build for npm publishing
      - run: npm ci
      - run: npm run build

      # Dry run NPM publish
      - name: Dry run NPM publish
        run: npm publish --tag ${{ inputs.channel }} --provenance --access public --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.HD_CLI_NPM_TOKEN }}
